### ISSUE TITLE
Installation issue with script regarding pacman

### ISSUE THREAD

**Issue by ramandelbaum** [ocdy1001/LinuxRice#10]
When I give chmod permission and run the script for arch - I get the following error:
"config file /etc/pacman.d/mirrorlist-arch could not be read: No such file or directory"
my arch system was up to date prior to running script and now I'm unable to run pacman on my laptop

**Comment by codybloemhard** [comment]
Hey, sorry to hear that. I think the issue is that the pacman config in my dotfiles is meant for Artix linux and not for Arch. I shall look into making it more clear or updating the instructions. But first let's get your system up and running again. The pacman config lives at `/etc/pacman.conf`. This is has now the faulty config my script put there. You can replace it with a standard Arch linux config that can be found here: https://github.com/archlinux/svntogit-packages/blob/packages/pacman/trunk/pacman.conf. That should make pacman work again. Let me know if that doesn't fix it.

**Comment by codybloemhard** [comment]
On a more general note, installing someones dotfiles as might not be the best thing to do even if it works and doesn't brick your system (sorry). For example I have some very specific things like settings the audio device to an external dac, keybindings are design for the QGMLWY keyboard layout, a very personal opinionated neovim config, etc. I would look through the install and config scripts to remove or change some things as you see fit for your system (for example the arch repos don't need to be installed on arch). I'll make some adjustment so what happened to you doesn't happen to anyone else in the future.

**Comment by ramandelbaum** [comment]
It’s okay!
I did some trouble shooting / looking around the arch forums and was able
to restore the proper mirror list for pacman to properly work. I had an
interesting issue happen when I ran it again - when I rebooted my laptop
arch failed to launch stating it could not load the Linux kernel or
something of that nature. The laptop would fail to boot and I’d have to
restart it.

I’m still new to using arch and couldn’t figure out how to fix it using
arch-chroot while in the live usb so I just did a fresh install. I didn’t
lose anything important as I’m really using my laptop as a learning
experience so I was expecting to break it one way or another.

All that being said - I’m gonna read through the actual config file for
your i3-gap and see what parts of it I like and go about doing it that way.

Thanks for the reply man! Have a good one

**Comment by codybloemhard** [comment]
I'm glad to hear that nothing of importance was lost to you. A little information for your learning experience if I may, the faulty config was looking for a mirrorlist file that wasn't there, and shouldn't be there. By putting a mirrorlist there, it might seem that pacman was working again but in reality it was misconfigured. Running a misconfigured pacman might have done in your system. In short, you restored a mirrorlist but you should have restored the pacman config. Again, just for your understanding. I wish you luck on your Arch Linux journey.

**Comment by ramandelbaum** [comment]
That’s good to know, thank you!
In the future I’ll try stuff on a virtual machine first for headaches sake.
I’m stubborn so I want to see it I can make something work haha.

Thank you again for the info, I’m leaving my star up because it’s a cool
idea to easily import your settings /  preferences onto a fresh install of
your OS incase your computer dies.
